site_name: godi
site_url: https://byron.github.io/godi
site_description: Fast data integrity verification

repo_url: https://github.com/Byron/godi
dev_addr: 127.0.0.1:9995

docs_dir: ../../src/md
site_dir: ../../doc/mkdocs/html

pages:
- ['index.md', 'Home']
- ['usage.md', 'Learn', 'How to Use Godi']
- ['details.md', 'Learn', 'About Details']
- ['proprietary.md', 'Learn', 'About Others']
- ['contributing.md', 'Contribute', 'How to Contribute']
- ['development.md', 'Contribute', 'From within the Machine']
- ['license.md', 'About', 'License']

theme: yeti

copyright: Copyright &copy; 2014, <a href="https://www.linkedin.com/in/sebastianthiel">Sebastian Thiel & Contributors</a>.
